
GameData= {
        "Ninjas":{
            "Fire":{
                "HP":100,
                "Range":2,
                "Attack":8,
                "Move":2,
                "AniAttack":"",
                "AniMove":"",
                "AniSpecial":"",
                "BasePosition":{
                    "z":10,
                    "y":10
                }
            },
            "Snow":{
                "HP":100,
                "Range":3,
                "Attack":6,
                "Move":3,
                "AniAttack":"",
                "AniMove":"",
                "AniSpecial":"",
                "BasePosition":{
                    "z":10,
                    "y":10
                }
            },
            "Water":{
                "HP":100,
                "Range":1,
                "Attack":10,
                "Move":2,
                "AniAttack":"",
                "AniMove":"",
                "AniSpecial":"",
                "BasePosition":{
                    "z":10,
                    "y":10
                }
            }
        },
        "Enemies":{
            "Sly":{
                "HP":30,
                "IDDesign":"12",
                "Range":3,
                "Attack":4,
                "AniAttack":"",
                "AniMove":"",
                "Move":3,
                "Round1":{
                    "z":10,
                    "y":10
                },
                "Round2":{
                    "z":10,
                    "y":10
                },
                "Round3":{
                    "z":10,
                    "y":10
                }
            },
            "Tank":{
                "HP":60,
                "IDDesign":"12",
                "AniAttack":"",
                "AniMove":"",
                "Range":1,
                "Attack":10,
                "Move":1,
                "Round1":{
                    "z":10,
                    "y":10
                },
                "Round2":{
                    "z":10,
                    "y":10
                },
                "Round3":{
                    "z":10,
                    "y":10
                }
            },
            "Scrap":{
                "HP":45,
                "IDDesign":"12",
                "AniAttack":"",
                "AniMove":"",
                "Range":2,
                "Attack":5,
                "Move":2,
                "Round1":{
                    "z":10,
                    "y":10
                },
                "Round2":{
                    "z":10,
                    "y":10
                },
                "Round3":{
                    "z":10,
                    "y":10
                }
            }
        }
    }

